### ISSUE TITLE
Multi-Tap unable to show

### ISSUE THREAD

**Issue by Allen2Git** [purocean/vscode-drawio-preview#1]
Dear,

This extension is excellent. But when I open the .drawio file with multi-tap (multiple diagram id in mxfil) it's only display the first diagram. 
Will you add the support for multi-tap support?
Thanks.

Best regards,
Allen

**Comment by purocean** [comment]
Please upgrade to version 0.0.3.
![image](https://user-images.githubusercontent.com/7115690/79708459-05400680-82f2-11ea-9d28-97be222034e1.png)
