### ISSUE TITLE
error load .drawio files in vscode

### ISSUE THREAD

**Issue by Mohammad-Ravand** [purocean/vscode-drawio-preview#11]
i installed Drawio Preview extention on vscode
and create file name ER.drawio but does not previw any this, just is like text file showed for me.
![Drawio Preview](https://github.com/purocean/vscode-drawio-preview/assets/108149753/580a361f-02a0-4dd6-9b78-79260dfe01df)
![Drawio Preview](https://github.com/purocean/vscode-drawio-preview/assets/108149753/c2b000c0-4754-4a11-87f7-7d795c7b2f42)

**Comment by purocean** [comment]
![image](https://github.com/purocean/vscode-drawio-preview/assets/7115690/ba30c418-2732-4389-8d3f-57d99d4bc75d)

@Mohammad-Ravand Please click this button

This extension is just a previewer

**Comment by Mohammad-Ravand** [comment]
thanks i just have to close the vscode and restart  agait , it works fine.
