### ISSUE TITLE
Source of the viewer.min.js file?

### ISSUE THREAD

**Issue by vallamost** [purocean/vscode-drawio-preview#6]
First off, awesome job on the plugin! :)

The point of this issue:
The viewer.min.js file linked below looks sketchy. 
https://github.com/purocean/vscode-drawio-preview/blob/master/assets/viewer.min.js

I see it is mentioning https://viewer.diagrams.net/ which I think is the creator of DrawIO. Where did the rest of the obfuscated javascript come from? Was it from their site? Why not load their file directly from them with an HTTP request instead of using a copied version that could include obfuscated malware?

**Comment by purocean** [comment]
When I wrote this plugin, I simply copied the code from another project of mine (which needs to be run offline). Indeed this is flawed, for example, the new version of the drawio file cannot be displayed well. I will switch to the official link.

**Comment by purocean** [comment]
use git submodule https://github.com/purocean/vscode-drawio-preview/commit/58bd4aadeafd1a7af22bda0fedbe15bedb001ab2
